# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: VortexDownloader.VortexDownloader
PackageVersion: 1.1.3
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /currentuser /S
  SilentWithProgress: /currentuser /S
UpgradeBehavior: install
Protocols:
- magnet
FileExtensions:
- 3gp
- aac
- avi
- flac
- flv
- m4a
- m4v
- mkv
- mov
- mp3
- mp4
- ogg
- opus
- ts
- wav
- webm
- wmv
ProductCode: 60e49f43-1ca6-5921-9e6c-231e73718a88
Installers:
- Architecture: x64
  InstallerUrl: https://vortexdownloader.org/downloads/Vortex-Downloader-Setup.exe
  InstallerSha256: E61D27DEB21DE588A57167D8A85DACF7CF324F33A6375E0DF10235A48C041C39
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-09-27
